//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitWindows {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoActivate {
            get {
                return ((bool)(this["autoActivate"]));
            }
            set {
                this["autoActivate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int marginLeft {
            get {
                return ((int)(this["marginLeft"]));
            }
            set {
                this["marginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int marginTop {
            get {
                return ((int)(this["marginTop"]));
            }
            set {
                this["marginTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int marginRight {
            get {
                return ((int)(this["marginRight"]));
            }
            set {
                this["marginRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int marginBottom {
            get {
                return ((int)(this["marginBottom"]));
            }
            set {
                this["marginBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte cascadeMinWindows {
            get {
                return ((byte)(this["cascadeMinWindows"]));
            }
            set {
                this["cascadeMinWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("533")]
        public int cascadeMinWidthPix {
            get {
                return ((int)(this["cascadeMinWidthPix"]));
            }
            set {
                this["cascadeMinWidthPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int cascadeMinHeightPix {
            get {
                return ((int)(this["cascadeMinHeightPix"]));
            }
            set {
                this["cascadeMinHeightPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.33")]
        public double cascadeMinWidthPct {
            get {
                return ((double)(this["cascadeMinWidthPct"]));
            }
            set {
                this["cascadeMinWidthPct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.33")]
        public double cascadeMinHeightPct {
            get {
                return ((double)(this["cascadeMinHeightPct"]));
            }
            set {
                this["cascadeMinHeightPct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double cascadeColAdjHoriz {
            get {
                return ((double)(this["cascadeColAdjHoriz"]));
            }
            set {
                this["cascadeColAdjHoriz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double cascadeColAdjVert {
            get {
                return ((double)(this["cascadeColAdjVert"]));
            }
            set {
                this["cascadeColAdjVert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double cascadeBadWidthPct {
            get {
                return ((double)(this["cascadeBadWidthPct"]));
            }
            set {
                this["cascadeBadWidthPct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double cascadeBadHeightPct {
            get {
                return ((double)(this["cascadeBadHeightPct"]));
            }
            set {
                this["cascadeBadHeightPct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double tileMainViewMinWidthPct {
            get {
                return ((double)(this["tileMainViewMinWidthPct"]));
            }
            set {
                this["tileMainViewMinWidthPct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double tileMainViewMinHeightPct {
            get {
                return ((double)(this["tileMainViewMinHeightPct"]));
            }
            set {
                this["tileMainViewMinHeightPct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double tileSideViewWidthIncreasePct {
            get {
                return ((double)(this["tileSideViewWidthIncreasePct"]));
            }
            set {
                this["tileSideViewWidthIncreasePct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double tileSideViewHeightIncreasePct {
            get {
                return ((double)(this["tileSideViewHeightIncreasePct"]));
            }
            set {
                this["tileSideViewHeightIncreasePct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double tileSideViewSizeAdjustAmt {
            get {
                return ((double)(this["tileSideViewSizeAdjustAmt"]));
            }
            set {
                this["tileSideViewSizeAdjustAmt"] = value;
            }
        }
    }
}
